
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Complete(

		//////////// CLOCK //////////
		input 	     ADC_CLK_10,
		input 	     MAX10_CLK1_50,
		input 	     MAX10_CLK2_50,

		//////////// SEG7 //////////
		output [7:0] HEX0,
		output [7:0] HEX1,
		output [7:0] HEX2,
		output [7:0] HEX3,
		output [7:0] HEX4,
		output [7:0] HEX5,

		//////////// KEY //////////
		input [1:0]  KEY,

		//////////// LED //////////
		output [9:0] LEDR,

		//////////// SW //////////
		input [9:0]  SW
		);



   //=======================================================
   //  REG/WIRE declarations
   //=======================================================

   wire 		     one_hz_clk;
   wire 		     two_hz_clk;
   wire 		     out_hz_clk;
   wire 		     clk_sel;
   wire [3:0] 		     lsd;
   wire [3:0] 		     msd;
   wire 		     reset_n;
   wire 		     latch;
   wire 		     ms_off;

   wire [4:0] 		     day;

   wire [3:0] 		     month;
   wire [7:0] 		     cnt;
   

   
   
   assign LEDR[1] = out_hz_clk;
   assign LEDR[0] = reset_n;
   assign count = {msd, lsd};
   //=======================================================
   //  Structural coding
   //=======================================================

   
   latch_key L1 (
		 .KEY (KEY[0]),
		 .R (reset_n)
		 );
   

   latch_key Clk (
		  .KEY (KEY[1]),
		  .R (clk_sel)
		  );
   
   
   
   
   clock_div_1hz C1 (
		     .reset_n (reset_n),
		     .src_clk (ADC_CLK_10),
		     .out_clk (one_hz_clk)
		     );
   clock_div_2hz C2 (
		     .reset_n (reset_n),
		     .src_clk (ADC_CLK_10),
		     .out_clk (two_hz_clk)
		     );
   clock_mux S1 (
		 .a(one_hz_clk),
		 .b(two_hz_clk),
		 .sel(clk_sel),
		 .out(out_hz_clk)
		 );
   
   
   bcd_counter U1 (
		   .reset_n (reset_n),
		   .src_clk (out_hz_clk),
		   .msd_out (msd),
		   .cnt_out (cnt),
		   .lsd_out (lsd)
		   );
   
   day_drive D1 (
		 .day(day),
		 .HEX0(HEX0),
		 .HEX1(HEX1)
		 );
   
   
   month_day M1 (
		 .lsd(lsd),
		 .msd(msd),
		 .count(cnt),
		 .leap_year(SW[9]),
		 .day(day),
		 .month(month)
		 );

   hex_driver X2 (
		  .NUM(month),
		  .HEX(HEX2)
		  );

   hex_driver X3 (
		  .NUM(4'b0000),
		  .HEX(HEX3),
		  .OFF(1'b1)
		  );
   
   hex_driver X4 (
		  .NUM(lsd),
		  .HEX(HEX4)
		  );
   
   
   hex_driver X5 (
		  .NUM(msd),
		  .HEX(HEX5),
		  .OFF(1'b1)
		  );
   
endmodule
